In [49]:
import pandas as pd
import numpy as np
import scipy.cluster.hierarchy as sch
import data_managment as dm
from sklearn.impute import KNNImputer
from sklearn.cluster import KMeans

In [3]:
data=pd.read_csv("~/Documents/iaprojet/IA_project/data.txt", sep="\t")
dat=data.drop(columns=["Country Code","Series Code","Country Name"])
data

,Country Name,Country Code,Series Name,Series Code,2016 [YR2016]
0,Afghanistan,AFG,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,1000
1,Afghanistan,AFG,"Adolescents out of school, male (% of male low...",SE.SEC.UNER.LO.MA.ZS,..
2,Afghanistan,AFG,Oil rents (% of GDP),NY.GDP.PETR.RT.ZS,0.000866608364478627
3,Afghanistan,AFG,People practicing open defecation (% of popula...,SH.STA.ODFC.ZS,13.6430225
4,Afghanistan,AFG,CO2 emissions (kt),EN.ATM.CO2E.KT,5300.00019073486
...,...,...,...,...,...
2821,NaN,NaN,NaN,NaN,NaN
2822,NaN,NaN,NaN,NaN,NaN
2823,NaN,NaN,NaN,NaN,NaN
2824,Data from database: World Development Indicators,NaN,NaN,NaN,NaN
2825,Last Updated: 12/22/2022,NaN,NaN,NaN,NaN

In [7]:
d=data["2016 [YR2016]"]
l=[]
i=0
while i<len(d):
    j=d.to_list()[i:i+13]
    l.append(j)
    i+=13

q=pd.DataFrame(l)
q

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1000,..,0.000866608364478627,13.6430225,5300.00019073486,319.029,..,..,3.6802510519657,2,..,..,..
1,100,5.90330982208252,1.15651054126866,0.080385895,4480.00001907349,161.348,..,..,3.78723434007733,..,..,..,..
2,1900,..,10.028258191437,0.900352486,154910.003662109,78741.491,..,..,15.3243976630882,..,..,..,..
3,..,..,0,0.703887113,..,..,..,..,..,..,..,..,..
4,..,..,..,0,469.999998807907,0,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,..,9.22638988494873,0,0.190395705,..,0,..,..,..,..,..,..,..
214,870,22.6338596343994,0.681565886623517,14.20944734,10850.0003814697,986.423,..,..,..,1.5,..,..,..
215,61000,..,0,14.29453323,5320.00017166138,0,..,..,5.97346587502659,3,..,..,..
216,44000,..,0,25.08279239,11020.0004577637,0,..,..,184.076187538556,2,..,..,..
217,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None

In [46]:
df = dm.build_adapted_df(data)
df

Country Name,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,...,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe
Series Name,,,,,,,,,,,,,,,,,,,,,
"Adolescents out of school, male (% of male lower secondary school age)",NaN,5.903310,NaN,NaN,NaN,NaN,5.570900,0.138270,7.776090,NaN,...,1.305430,4.398410,NaN,10.698010,NaN,NaN,9.226390,22.633860,NaN,NaN
Adults (ages 15+) and children (ages 0-14) newly infected with HIV,1000.000000,100.000000,1900.000000,NaN,NaN,23000.000000,NaN,5500.000000,NaN,NaN,...,810.000000,4300.000000,NaN,NaN,9400.000000,NaN,NaN,870.000000,61000.000000,44000.000000
CO2 emissions (kt),5300.000191,4480.000019,154910.003662,NaN,469.999999,29760.000229,500.000000,183160.003662,5070.000172,NaN,...,6519.999981,105230.003357,180.000007,151070.007324,223720.001221,NaN,NaN,10850.000381,5320.000172,11020.000458
CO2 emissions from gaseous fuel consumption (kt),319.029000,161.348000,78741.491000,NaN,0.000000,1496.136000,0.000000,102268.963000,4191.381000,0.000000,...,106.343000,75012.152000,0.000000,48796.769000,20384.853000,NaN,0.000000,986.423000,0.000000,0.000000
"CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)",2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.000000,3.000000,NaN,NaN,NaN,NaN,1.500000,3.000000,2.000000
Child employment in manufacturing (% of economically active children ages 7-14),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Child employment in manufacturing, female (% of female economically active children ages 7-14)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Child employment in manufacturing, male (% of male economically active children ages 7-14)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Military expenditure (% of general government expenditure),3.680251,3.787234,15.324398,NaN,NaN,12.399960,NaN,1.948955,15.122662,NaN,...,5.792367,NaN,NaN,NaN,8.774190,NaN,NaN,NaN,5.973466,184.076188
Oil rents (% of GDP),0.000867,1.156511,10.028258,0.000000,NaN,10.325724,0.000000,0.536795,0.000000,0.000000,...,0.000000,0.404197,0.000000,NaN,1.064871,0.0,0.000000,0.681566,0.000000,0.000000
People practicing open defecation (% of population),13.643023,0.080386,0.900352,0.703887,0.000000,21.226596,0.264129,NaN,0.011157,1.473163,...,0.503675,0.000000,0.581828,3.402714,3.007105,0.0,0.190396,14.209447,14.294533,25.082792

In [58]:
imputer = KNNImputer(missing_values=np.nan)
imputed_DF = pd.DataFrame(imputer.fit_transform(df))
imputed_DF.columns = df.columns
imputed_DF.index = df.index
imputed_DF

Country Name,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,...,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe
Series Name,,,,,,,,,,,,,,,,,,,,,
"Adolescents out of school, male (% of male lower secondary school age)",203.864828,5.903310,16133.548802,0.351944,156.666666,4908.017656,5.570900,0.138270,7.776090,0.491054,...,1.305430,4.398410,36.716367,10.698010,5959.539833,0.0,9.226390,22.633860,12204.653600,8842.231796
Adults (ages 15+) and children (ages 0-14) newly infected with HIV,1000.000000,100.000000,1900.000000,0.351944,156.666666,23000.000000,101.167006,5500.000000,842.858182,0.491054,...,810.000000,4300.000000,36.716367,49970.219262,9400.000000,0.0,2.354196,870.000000,61000.000000,44000.000000
CO2 emissions (kt),5300.000191,4480.000019,154910.003662,0.351944,469.999999,29760.000229,500.000000,183160.003662,5070.000172,0.491054,...,6519.999981,105230.003357,180.000007,151070.007324,223720.001221,0.0,2.354196,10850.000381,5320.000172,11020.000458
CO2 emissions from gaseous fuel consumption (kt),319.029000,161.348000,78741.491000,0.351944,0.000000,1496.136000,0.000000,102268.963000,4191.381000,0.000000,...,106.343000,75012.152000,0.000000,48796.769000,20384.853000,0.0,0.000000,986.423000,0.000000,0.000000
"CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)",2.000000,34.455088,16133.548802,0.351944,156.666666,4908.017656,101.167006,21554.317404,842.858182,0.491054,...,22.788895,2.000000,3.000000,49970.219262,5959.539833,0.0,2.354196,1.500000,3.000000,2.000000
Child employment in manufacturing (% of economically active children ages 7-14),267.270628,22.185488,16133.548802,0.351944,156.666666,4908.017656,101.167006,21554.317404,842.858182,0.491054,...,163.520295,15863.390921,36.716367,49970.219262,5959.539833,0.0,2.354196,378.789575,12204.053600,8841.831796
"Child employment in manufacturing, female (% of female economically active children ages 7-14)",267.270628,22.185488,16133.548802,0.351944,156.666666,4908.017656,101.167006,21554.317404,842.858182,0.491054,...,163.520295,15863.390921,36.716367,49970.219262,5959.539833,0.0,2.354196,378.789575,12204.053600,8841.831796
"Child employment in manufacturing, male (% of male economically active children ages 7-14)",267.270628,22.185488,16133.548802,0.351944,156.666666,4908.017656,101.167006,21554.317404,842.858182,0.491054,...,163.520295,15863.390921,36.716367,49970.219262,5959.539833,0.0,2.354196,378.789575,12204.053600,8841.831796
Military expenditure (% of general government expenditure),3.680251,3.787234,15.324398,0.351944,156.666666,12.399960,101.167006,1.948955,15.122662,0.491054,...,5.792367,861.360521,36.716367,49970.219262,8.774190,0.0,2.354196,181.804975,5.973466,184.076188
Oil rents (% of GDP),0.000867,1.156511,10.028258,0.000000,156.666666,10.325724,0.000000,0.536795,0.000000,0.000000,...,0.000000,0.404197,0.000000,49970.219262,1.064871,0.0,0.000000,0.681566,0.000000,0.000000
People practicing open defecation (% of population),13.643023,0.080386,0.900352,0.703887,0.000000,21.226596,0.264129,21554.317404,0.011157,1.473163,...,0.503675,0.000000,0.581828,3.402714,3.007105,0.0,0.190396,14.209447,14.294533,25.082792

In [60]:
Z = sch.linkage(imputed_DF, method='complete', metric='euclidean')
#kmEngine = KMeans(n_clusters=8,init="k-means++", n_init=10, max_iter=300,tol=0.0001, random_state=200)
#kmeans=kmEngine.fit(q)
fig = plt.figure(figsize=(20, 40))
dendro = sch.dendrogram(Z, orientation='left', leaf_rotation=0, leaf_font_size=15)

NameError: name 'plt' is not defined